package com.example.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

@Data // Generates getters, setters, toString, equals, hashCode methods
@NoArgsConstructor // Generates no-args constructor
@AllArgsConstructor // Generates constructor with all fields
@Entity
public class Book {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    private String title;
    private Date publishedDate;
    private String isbn;
    private Boolean availability;

    // Getters and setters are automatically generated by @Data
}
